FROM mcr.microsoft.com/dotnet/sdk:5.0 as build
WORKDIR /app
COPY ConversaoPeso.Web/*.csproj ./
RUN dotnet restore

COPY ./ConversaoPeso.Web/. ./
RUN dotnet publish -c release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "ConversaoPeso.Web.dll"]